name: 'ci'
on:
  pull_request:
    branches:
      - master
jobs:
  browser-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: yarn install

      - name: Run browser tests
        run: yarn run test:browser

  node-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: yarn install

      - name: Run node tests
        run: yarn run test:node
